# Site settings
title: Blog
header-img: img/home-bg.jpg
email: zhxshseu@gmail.com
copyright_name: Haoson Zhao/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://zhxsh.xyz"

# SNS accounts
facebook_username:  hansonzhao007
twitter_username:   hansonzhao007
github_username:    hansonzhao007
linkedin_username:  hanson-xingsheng-zhao-043b3a82
email_username:     zhxshseu@gmail.com
weibo_username:     hansonzhao007
zhihu_username:     hansonzhao007
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Stay Hungry, Stay Foolish"
sidebar-avatar: /img/avatar-hanson.png      # use absolute URL, seeing it's used in both `/` and `/about/`

